foodOnline_main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as MarketplaceView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.home, name='home-page'),
    path("",include("accounts.urls")),
    path("marketplace/",include('marketplace.urls')),

    # searching
    path("search/", MarketplaceView.search, name="search"),

    # checkout
    path("checkout/",MarketplaceView.checkout, name="checkout"),

    # orders
    path("orders/",include("orders.urls"))

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('place-order/',views.place_order, name="place_order"),
    path('payments/',views.payments, name="payments"),
    path('order-complete/',views.order_complete, name="order_complete"),
]

orders/models.py
import json
from django.db import models
from accounts.models import User
from menu.models import FoodItem
from vendor.models import Vendor

request_object = ''

class Payment(models.Model):
  PAYMENT_METHOD=(
    ('PayPal', 'PayPal'),
    ('RazorPay', 'RazorPay'),
  )
  user=models.ForeignKey(User, on_delete=models.CASCADE)
  transaction_id = models.CharField(max_length=100)
  payment_method = models.CharField(choices=PAYMENT_METHOD,max_length=100)
  amount = models.CharField(max_length=10)
  status = models.CharField(max_length=100)
  created_at  = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.transaction_id
  
class Order(models.Model):
  STATUS = (
    ('New','New'),
    ('Accepted','Accepted'),
    ('Completed','Completed'),
    ('Cancelled','Cancelled'),
  )

  user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
  payment = models.ForeignKey(Payment,on_delete=models.SET_NULL,blank=True,null=True)
  vendors = models.ManyToManyField(Vendor,blank=True)
  order_number = models.CharField(max_length=50)
  first_name = models.CharField(max_length=50)
  last_name = models.CharField(max_length=50)
  phone = models.CharField(max_length=50,blank=True)
  email = models.EmailField(max_length=254)
  address = models.CharField(max_length=250)
  country = models.CharField(max_length=25,blank=True)
  state = models.CharField(max_length=25,blank=True)
  city = models.CharField(max_length=50)
  pin_code = models.CharField(max_length=10)
  total = models.FloatField()
  tax_data = models.JSONField(blank=True,help_text="Data format:{'tax_type':{'tax_percentage':'tax_amount'}}",null=True)
  total_data = models.JSONField(blank=True,null=True)
  total_tax = models.FloatField()  
  payment_method = models.CharField(max_length=25)
  status= models.CharField(choices=STATUS, default='New')
  is_ordered = models.BooleanField(default=False)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  @property
  def name(self):
    return f'{self.first_name} {self.last_name}'
  
  def order_placed_to(self):
    return ", ".join([str(i) for i in self.vendors.all()])

  def get_total_by_vendor(self):
    vendor  = Vendor.objects.get(user=request_object.user)
    subtotal=0
    tax_dict = {}
    tax=0

    if self.total_data:
      total_data = self.total_data
      data = total_data.get(str(vendor.id))
      
      for key, value in data.items():
        subtotal += float(key)
        value = value.replace("'",'"')
        value = json.loads(value)
        tax_dict.update(value)

        for i in value:
          for j in value[i]:
            tax += float(value[i][j])

    grand_total = float(subtotal) + float(tax)    
    
    context={
      'subtotal':subtotal,
      'tax_dict':tax_dict,
      'tax':tax,
      'grand_total':grand_total
    }
            
     
    return context
  
  def __str__(self):
    return self.order_number
  
class OrderedFood(models.Model):
  order = models.ForeignKey(Order, on_delete=models.CASCADE)
  payment = models.ForeignKey(Payment, on_delete=models.SET_NULL,blank=True,null=True)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  fooditem = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
  quantity = models.IntegerField()
  price= models.FloatField()
  amount = models.FloatField()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.fooditem.food_title
  

  

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>FoodOnline</title>
	<!-- Google Font Family Link Start -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
	<!-- Google Font Family Link End -->

	<!-- CSS -->
	<link href="{% static "main/css/iconmoon.css" %}" rel="stylesheet">
	<link href="{% static "main/css/style.css" %}" rel="stylesheet">
	<link href="{% static "main/css/cs-foodbakery-plugin.css" %}" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link href="{% static "main/css/bootstrap-slider.css" %}" rel="stylesheet">
	
	<!-- JAVASCRIPT -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="{% static "main/js/modernizr.js" %}"></script>
	<script src="{% static "main/js/bootstrap.js" %}"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	
	
	<link rel="stylesheet" href="{% static "main/css/custom.css" %}">
	
	{% if '/profile/' in request.GET %}
	<script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete" async defer></script>
	{% endif %}
	<script src="{% static "main/js/custom.js" %}"></script>
	<!-- include datatable plugin using jquery -->
	 <link rel="stylesheet" href="//cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css">
	 <script src="//cdn.datatables.net/2.1.8/js/dataTables.min.js"></script>
	 <script>
		$(document).ready(function(){
			$('#myOrdersTable').DataTable();
		})
	 </script>
	<style>
		body, .main-section p, .mce-content-body p{
			font:Normal  14px/24px "Open Sans", sans-serif;letter-spacing: 0px;text-transform: none;color: #515151 !important;
		}
	</style>
</head>

<body>

  {% comment %} load navbar/header {% endcomment %}
  {% include "includes/navbar.html" %}

  {% block content %}
    {% comment %} content goes here {% endcomment %}
  {% endblock %}
  
  {% comment %} load footer here {% endcomment %}
  {% include "includes/footer.html" %}

	
	

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- Main Section Start -->
	<div class="main-section">
		<!-- Home Pages Elements Strat -->
		<!-- Main Search Start -->
		<div class="page-section nopadding cs-nomargin" style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url({% static "main/extra-images/bg-image1.jpg" %}) no-repeat center / cover;">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
						<div class="element-title">
							<h1 style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
								We are in the business of food<br>our restaurants do</h1>
							<p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
								Ridiculus sociosqu
								cursus neque cursus curae ante scelerisque vehicula.</p>
						</div>
					</div>
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
						<div class="main-search fancy bg-holder">
							<form action="{% url "search" %}" method='GET'>
								<div class="row">
									<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12">
										<div class="field-holder">
											<input type="text" name="keyword" placeholder="Resturant name Or Food Name">
										</div>
									</div>
									<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
										<div class="field-holder">
											<ul>
												<li class="select-location">
													<div class="foodbakery-locations-fields-group foodbakery-focus-out">
														<span class="foodbakery-search-location-icon"><i class="icon-location"></i></span>
														<input type="text" id="id_address" name="address" class="location-field-text filter" placeholder="All Locations">
														<input type="hidden" id="id_latitute" name="lat" value="{{request.user.userprofile.latitude}}"  placeholder="All Locations">
														<input type="hidden" id="id_longitude" name="lng" value="{{request.user.userprofile.longtitude}}" placeholder="All Locations">
													</div>
													
												</li>
											</ul>
										</div>
									</div>
									<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
										<div class="field-holder">
											<select name="radius" id="radius" style="height:50px;" required>
												<option value="" selected>Choose Radius</option>
												<option value="5">5 Km</option>
												<option value="10">10 Km</option>
												<option value="15">15 Km</option>
												<option value="25">25 Km</option>
												<option value="50">50 Km</option>
												<option value="75">75 Km</option>
												<option value="100">100 Km</option>
											</select>
										</div>
									</div>
									<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
										<div class="field-holder">
											<input type="submit" value="Search">
										</div>
									</div>
								</div>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		<!-- Main Search End -->
		
		<!-- Top Restarurants Section Start -->
		<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="element-title align-left">
							<h2>Top Restaurants</h2>
							<p>Explore restaurants, bars, and cafés by locality</p>
						</div>
					</div>
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="padding-right:0 !important; padding-left:0 !important;">
						<div class="company-logo">
							<ul>
								{% for vendor in vendors %}
								<li class="has-border">
									<figure>
										<a href="{% url "vendor_detail" vendor.vendor_slug %}">
											{% if vendor.user_profile.profile_picture %}
											<img src="{{vendor.user_profile.profile_picture.url}}" class="attachment-full size-full wp-post-image" alt=""></a>
											{% else %}
											<img src="{% static "main/images/default-profile.png" %}" class="attachment-full size-full wp-post-image" alt=""></a>
											{% endif %}
									</figure>
								</li>
								{% endfor %}
								
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Top Restarurants Section End -->
		<!-- Choose From Most Popular Listin Start -->
		<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="element-title align-center">
							<h2>Choose From Most Popular Restaurants</h2>
							<p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
						</div>
					</div>
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="listing fancy">
							<ul class="row">
								{% for vendor in vendors %}								<li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
									<div class="list-post featured">
										<div class="img-holder">
											<figure>
												<a href="{% url "vendor_detail" vendor.vendor_slug %}">
													{% if vendor.user_profile.profile_picture %}
														<img src="{{vendor.user_profile.profile_picture.url}}" class="img-thumb wp-post-image" alt="">
													{% else %}
														<img src="{% static "main/extra-images/listing-logo18.png" %}" class="img-thumb wp-post-image" alt="">
													{% endif %}
												</a>
										</figure>
											<span class="restaurant-status {% if vendor.user.is_active %} open {% else %} close {% endif %}">
												<em class="bookmarkRibbon"></em>
												{% if vendor.user.is_active %}
													OPEN
												{% else %}
													CLOSE
												{% endif %}
											</span>
										</div>
										<div class="text-holder">
											
											<div class="post-title">
												<h5>
													<a href="{% url "vendor_detail" vendor.vendor_slug %}">{{vendor.vendor_name}}</a>
													<span class="sponsored text-color">Sponsored</span>
												</h5>
											</div>
											{% if vendor.user_profile.city and vendor.user_profile.state and vendor.user_profile.pin_code %}
											<span>{{vendor.user_profile.city}} {{vendor.user_profile.state}} {{vendor.user_profile.pin_code}}</span>
											{% endif %}

												{% comment %} {% if lat %} {% endcomment %}
												<br>
												<span><small><b>{{vendor.kms}}km</b> away</small></span>
												{% comment %} {% endif %} {% endcomment %}
											
											
										</div>
										
									</div>
								</li>
								{% endfor %}

							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Choose From Most Popular Listing End -->

		<!-- Home Pages Elements End  -->
	</div>
	<!-- Main Section End -->

	{% comment %} <script>
		var current_locate = sessionStorage.getItem("current_location");
    if(current_locate != ''){
      latlng_list = current_locate.split(',')
      document.getElementById("id_latitute").value=latlng_list[0]
      document.getElementById("id_longitude").value=latlng_list[1]
    }
	</script> {% endcomment %}
	
	{% endblock %}